name: Run Guedesmoney CLI

on:
    workflow_dispatch:
        inputs:
            param1:
                    description: "Parameter 1"
                    required: true
                    default: true
                    type: boolean
            param2:
                description: "Parameter 2"
                required: true
                default: true
                type: boolean

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.8

            - name: Install Guedesmoney
              run: |
                python -m pip install --upgrade pip
                pip install guedesmoney

            - name: Checking GuedesMoney version
              run: "guedesmoney version"
            
            - name: Configure GuedesMoney
              run: "guedesmoney config -un ${{secrets.GUEDESMOENY_USER_NIF}} -up 321 -et gmail -se sender@sender.com -sp sender_pass -rl rec@rec.com"

            - name: Check GuedesMoney Configuration
              run: "guedesmoney config -c -shp"
            
            - name: Running CLI
              run: |
                echo "Running CLI"
                echo "param1: ${{github.event.inputs.param1}}"
                echo "param1: ${{github.event.inputs.param2}}"