name: Run Guedesmoney CLI

on:
    workflow_dispatch:
        inputs:
            check_fiscal:
                    description: "Check Fiscal Situation"
                    required: true
                    default: true
                    type: boolean
            check_alerts:
                description: "Check Alerts"
                required: true
                default: true
                type: boolean
            check_messages:
                description: "Check Messages"
                required: true
                default: true
                type: boolean
            check_interactions:
                description: "Check Interactions"
                required: true
                default: true
                type: boolean
            check_payments:
                description: "Check Payments"
                required: true
                default: true
                type: boolean
            current_payments:
                description: "Check Current Payments"
                required: true
                default: true
                type: boolean
            missing_payments:
                description: "Check Missing Payments"
                required: true
                default: true
                type: boolean
            refund_payments:
                description: "Check Refund Payments"
                required: true
                default: true
                type: boolean
            send_email:
                description: "Send Email"
                required: true
                default: true
                type: boolean

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.8

            - name: Install Guedesmoney
              run: |
                python -m pip install --upgrade pip
                pip install guedesmoney

            - name: Checking GuedesMoney version
              run: "guedesmoney version"
            
            - name: Configure GuedesMoney
              run: "guedesmoney config -un ${{secrets.GUEDESMOENY_USER_NIF}} -up ${{secrets.GUEDESMOENY_USER_PASSWORD}} -et ${{secrets.GUEDESMOENY_EMAIL_PROVIDER}} -se ${{secrets.GUEDESMOENY_EMAIL_SENDER}} -sp ${{secrets.GUEDESMOENY_SENDER_PASSKEY}} -rl ${{secrets.GUEDESMOENY_RECEPIENT_LIST}}"

            - name: Check GuedesMoney Configuration
              run: "guedesmoney config -c"
            
            - name: Running CLI
              run: |
                echo "Running CLI"
                guedesmoney run --headless --save_results --screenshot ${{ github.event.inputs.check_fiscal == 'true' && '--check-fiscal' || '' }} ${{ github.event.inputs.check_alerts == 'true' && '--check-alerts' || '' }} ${{ github.event.inputs.check_messages == 'true' && '--check-messages' || '' }} ${{ github.event.inputs.check_interactions == 'true' && '--check-interactions' || '' }} ${{ github.event.inputs.check_payments == 'true' && '--check-payments' || '' }} ${{ github.event.inputs.current_payments == 'true' && '--current' || '' }} ${{ github.event.inputs.missing_payments == 'true' && '--missing' || '' }} ${{ github.event.inputs.refund_payments == 'true' && '--refund' || '' }} ${{ github.event.inputs.send_email == 'true' && '--send-email' || '' }}