name: Hello World Action

on:
  schedule:
    # This will run 18:25 every day
    - cron:  '0 19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello World
      run: echo Hello, world!
